name: Java CI

on:
  push:
  release:
      types: # This configuration does not affect the page_build event above
        - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle        
      - name: Build with Gradle
        run: ./gradlew clean test build